/** Declaration file generated by dts-gen */

export function addMiddleware(...args: any[]): void;

export function removeMiddleware(middleware: any): any;

export function resetMiddlewares(): void;

export namespace addMiddleware {
    const prototype: {
    };

}

export namespace removeMiddleware {
    const prototype: {
    };

}

export namespace resetMiddlewares {
    const prototype: {
    };

}

